<<<<<<< HEAD
INSERT INTO public.exercises (name, category, duration_minutes, calories_burned, logged_at)
VALUES
('Running (moderate pace)', 'Cardio', 30, 320.50, now() - interval '1 day'),
('Cycling', 'Cardio', 45, 400.00, now() - interval '2 days'),
('Jump Rope', 'Cardio', 15, 180.75, now() - interval '3 days'),

('Push Ups', 'Strength', 20, 150.00, now() - interval '1 day'),
('Weight Lifting (Upper Body)', 'Strength', 50, 350.00, now() - interval '2 days'),
('Squats', 'Strength', 25, 200.00, now() - interval '4 days'),



('Football Match', 'Sports', 60, 600.00, now() - interval '5 days'),
('Basketball Game', 'Sports', 50, 520.00, now() - interval '2 days'),
('Tennis Practice', 'Sports', 30, 300.00, now() - interval '1 day');
=======
CREATE TABLE remember_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);
>>>>>>> 0ff852cebe70822885de07d5ffcf7467d6fc8d8c
