drop table if exists public.remember_tokens;

create table public.remember_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token varchar(255) not null,
    expires_at timestamp not null,
    foreign key (user_id) references public.users(id) on delete cascade
);
