CREATE TABLE meals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT  REFERENCES users(id) ON DELETE CASCADE,
    food_name VARCHAR(100),
    meal_type VARCHAR(50),
    calories INT,
    protein INT,
    carbs INT,
    fat INT,
    date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE exercise_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    exercise_name VARCHAR(100),
    duration INT,
    calories_burned INT,
    date DATE DEFAULT CURRENT_DATE
);